//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoBuffer/Camp.proto
// Note: requires additional types generated from: ProtoBuffer/ComProtocol.proto
// Note: requires additional types generated from: ProtoBuffer/ClientToServerCmd.proto
// Note: requires additional types generated from: Common/ComDefine.proto
namespace ProtoBuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CampProtoInfo")]
  public partial class CampProtoInfo : global::ProtoBuf.IExtensible
  {
    public CampProtoInfo() {}
    
    private int _camp_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"camp_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int camp_id
    {
      get { return _camp_id; }
      set { _camp_id = value; }
    }
    private string _leader_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"leader_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string leader_name
    {
      get { return _leader_name; }
      set { _leader_name = value; }
    }
    private string _notice = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"notice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string notice
    {
      get { return _notice; }
      set { _notice = value; }
    }
    private ulong _notice_cd = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"notice_cd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong notice_cd
    {
      get { return _notice_cd; }
      set { _notice_cd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CampProtoRankInfo")]
  public partial class CampProtoRankInfo : global::ProtoBuf.IExtensible
  {
    public CampProtoRankInfo() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _fight = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"fight", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fight
    {
      get { return _fight; }
      set { _fight = value; }
    }
    private int _official = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"official", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int official
    {
      get { return _official; }
      set { _official = value; }
    }
    private int _knight = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"knight", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int knight
    {
      get { return _knight; }
      set { _knight = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CampProtoHonorInfo")]
  public partial class CampProtoHonorInfo : global::ProtoBuf.IExtensible
  {
    public CampProtoHonorInfo() {}
    
    private int _official = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"official", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int official
    {
      get { return _official; }
      set { _official = value; }
    }
    private int _knight = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"knight", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int knight
    {
      get { return _knight; }
      set { _knight = value; }
    }
    private uint _contribute = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"contribute", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint contribute
    {
      get { return _contribute; }
      set { _contribute = value; }
    }
    private uint _total_contribute = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"total_contribute", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint total_contribute
    {
      get { return _total_contribute; }
      set { _total_contribute = value; }
    }
    private uint _prestige = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"prestige", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint prestige
    {
      get { return _prestige; }
      set { _prestige = value; }
    }
    private uint _kill_enemy_camp = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"kill_enemy_camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint kill_enemy_camp
    {
      get { return _kill_enemy_camp; }
      set { _kill_enemy_camp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Camp_JoinReq")]
  public partial class Camp_JoinReq : global::ProtoBuf.IExtensible
  {
    public Camp_JoinReq() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Camp_JoinRsp")]
  public partial class Camp_JoinRsp : global::ProtoBuf.IExtensible
  {
    public Camp_JoinRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private ProtoBuf.CampProtoInfo _info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.CampProtoInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Camp_ChangeReq")]
  public partial class Camp_ChangeReq : global::ProtoBuf.IExtensible
  {
    public Camp_ChangeReq() {}
    
    private int _camp_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"camp_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int camp_id
    {
      get { return _camp_id; }
      set { _camp_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Camp_ChangeRsp")]
  public partial class Camp_ChangeRsp : global::ProtoBuf.IExtensible
  {
    public Camp_ChangeRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private ProtoBuf.CampProtoInfo _info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.CampProtoInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Camp_CampInfoReq")]
  public partial class Camp_CampInfoReq : global::ProtoBuf.IExtensible
  {
    public Camp_CampInfoReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Camp_CampInfoRsp")]
  public partial class Camp_CampInfoRsp : global::ProtoBuf.IExtensible
  {
    public Camp_CampInfoRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private ProtoBuf.CampProtoInfo _info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.CampProtoInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Camp_RankInfoReq")]
  public partial class Camp_RankInfoReq : global::ProtoBuf.IExtensible
  {
    public Camp_RankInfoReq() {}
    
    private int _rank_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rank_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rank_type
    {
      get { return _rank_type; }
      set { _rank_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Camp_RankInfoRsp")]
  public partial class Camp_RankInfoRsp : global::ProtoBuf.IExtensible
  {
    public Camp_RankInfoRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private int _rank_type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rank_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rank_type
    {
      get { return _rank_type; }
      set { _rank_type = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.CampProtoRankInfo> _info = new global::System.Collections.Generic.List<ProtoBuf.CampProtoRankInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.CampProtoRankInfo> info
    {
      get { return _info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Camp_HonorInfoReq")]
  public partial class Camp_HonorInfoReq : global::ProtoBuf.IExtensible
  {
    public Camp_HonorInfoReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Camp_HonorInfoRsp")]
  public partial class Camp_HonorInfoRsp : global::ProtoBuf.IExtensible
  {
    public Camp_HonorInfoRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private ProtoBuf.CampProtoHonorInfo _info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.CampProtoHonorInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Camp_PublishNoticeReq")]
  public partial class Camp_PublishNoticeReq : global::ProtoBuf.IExtensible
  {
    public Camp_PublishNoticeReq() {}
    
    private string _notice;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"notice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string notice
    {
      get { return _notice; }
      set { _notice = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Camp_PublishNoticeRsp")]
  public partial class Camp_PublishNoticeRsp : global::ProtoBuf.IExtensible
  {
    public Camp_PublishNoticeRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Camp_BroadNoticeRsp")]
  public partial class Camp_BroadNoticeRsp : global::ProtoBuf.IExtensible
  {
    public Camp_BroadNoticeRsp() {}
    
    private string _notice;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"notice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string notice
    {
      get { return _notice; }
      set { _notice = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CenterToLogic_CampCharInfo")]
  public partial class CenterToLogic_CampCharInfo : global::ProtoBuf.IExtensible
  {
    public CenterToLogic_CampCharInfo() {}
    
    private uint _charid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private int _camp_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"camp_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int camp_id
    {
      get { return _camp_id; }
      set { _camp_id = value; }
    }
    private int _official;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"official", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int official
    {
      get { return _official; }
      set { _official = value; }
    }
    private int _knight;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"knight", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int knight
    {
      get { return _knight; }
      set { _knight = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CenterToLogic_CheckNoticeCostReq")]
  public partial class CenterToLogic_CheckNoticeCostReq : global::ProtoBuf.IExtensible
  {
    public CenterToLogic_CheckNoticeCostReq() {}
    
    private uint _char_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"char_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint char_id
    {
      get { return _char_id; }
      set { _char_id = value; }
    }
    private int _camp_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"camp_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int camp_id
    {
      get { return _camp_id; }
      set { _camp_id = value; }
    }
    private uint _diamond;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicToCenter_CheckNoticeCostRsp")]
  public partial class LogicToCenter_CheckNoticeCostRsp : global::ProtoBuf.IExtensible
  {
    public LogicToCenter_CheckNoticeCostRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private uint _char_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"char_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint char_id
    {
      get { return _char_id; }
      set { _char_id = value; }
    }
    private int _camp_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"camp_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int camp_id
    {
      get { return _camp_id; }
      set { _camp_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}