//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoBuffer/Duplicate.proto
// Note: requires additional types generated from: ProtoBuffer/ComProtocol.proto
// Note: requires additional types generated from: ProtoBuffer/ClientToServerCmd.proto
// Note: requires additional types generated from: Common/ComDefine.proto
namespace ProtoBuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DupMonsStateProto")]
  public partial class DupMonsStateProto : global::ProtoBuf.IExtensible
  {
    public DupMonsStateProto() {}
    
    private uint _mons_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mons_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mons_id
    {
      get { return _mons_id; }
      set { _mons_id = value; }
    }
    private int _state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DupFightDataProto")]
  public partial class DupFightDataProto : global::ProtoBuf.IExtensible
  {
    public DupFightDataProto() {}
    
    private uint _cid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cid
    {
      get { return _cid; }
      set { _cid = value; }
    }
    private ulong _atk;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"atk", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong atk
    {
      get { return _atk; }
      set { _atk = value; }
    }
    private ulong _be_atk;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"be_atk", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong be_atk
    {
      get { return _be_atk; }
      set { _be_atk = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_InfoReq")]
  public partial class Duplicate_InfoReq : global::ProtoBuf.IExtensible
  {
    public Duplicate_InfoReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_InfoRsp")]
  public partial class Duplicate_InfoRsp : global::ProtoBuf.IExtensible
  {
    public Duplicate_InfoRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.DuplicateProto> _info = new global::System.Collections.Generic.List<ProtoBuf.DuplicateProto>();
    [global::ProtoBuf.ProtoMember(2, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.DuplicateProto> info
    {
      get { return _info; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoBuf.DuplicateGroupProto> _group = new global::System.Collections.Generic.List<ProtoBuf.DuplicateGroupProto>();
    [global::ProtoBuf.ProtoMember(3, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.DuplicateGroupProto> group
    {
      get { return _group; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _open_list = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"open_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> open_list
    {
      get { return _open_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_EnterReq")]
  public partial class Duplicate_EnterReq : global::ProtoBuf.IExtensible
  {
    public Duplicate_EnterReq() {}
    
    private int _duplicate_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"duplicate_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int duplicate_id
    {
      get { return _duplicate_id; }
      set { _duplicate_id = value; }
    }
    private int _area_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private ProtoBuf.Vector3PB _cur_pos = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cur_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.Vector3PB cur_pos
    {
      get { return _cur_pos; }
      set { _cur_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_EnterRsp")]
  public partial class Duplicate_EnterRsp : global::ProtoBuf.IExtensible
  {
    public Duplicate_EnterRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private int _duplicate_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"duplicate_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int duplicate_id
    {
      get { return _duplicate_id; }
      set { _duplicate_id = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _area = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"area", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> area
    {
      get { return _area; }
    }
  
    private int _mons_num = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"mons_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mons_num
    {
      get { return _mons_num; }
      set { _mons_num = value; }
    }
    private int _dup_sec = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"dup_sec", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dup_sec
    {
      get { return _dup_sec; }
      set { _dup_sec = value; }
    }
    private int _tower_hp = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"tower_hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tower_hp
    {
      get { return _tower_hp; }
      set { _tower_hp = value; }
    }
    private int _trans_num = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"trans_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int trans_num
    {
      get { return _trans_num; }
      set { _trans_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_ResultRsp")]
  public partial class Duplicate_ResultRsp : global::ProtoBuf.IExtensible
  {
    public Duplicate_ResultRsp() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _duplicate_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"duplicate_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int duplicate_id
    {
      get { return _duplicate_id; }
      set { _duplicate_id = value; }
    }
    private int _star = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int star
    {
      get { return _star; }
      set { _star = value; }
    }
    private int _exp = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _gold = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private ProtoBuf.RewardItemProto _reward = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.RewardItemProto reward
    {
      get { return _reward; }
      set { _reward = value; }
    }
    private ProtoBuf.RewardItemProto _flop = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"flop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.RewardItemProto flop
    {
      get { return _flop; }
      set { _flop = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_AutoFightReq")]
  public partial class Duplicate_AutoFightReq : global::ProtoBuf.IExtensible
  {
    public Duplicate_AutoFightReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_AutoFightRsp")]
  public partial class Duplicate_AutoFightRsp : global::ProtoBuf.IExtensible
  {
    public Duplicate_AutoFightRsp() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_FlopReq")]
  public partial class Duplicate_FlopReq : global::ProtoBuf.IExtensible
  {
    public Duplicate_FlopReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_FlopRsp")]
  public partial class Duplicate_FlopRsp : global::ProtoBuf.IExtensible
  {
    public Duplicate_FlopRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_UpdateRsp")]
  public partial class Duplicate_UpdateRsp : global::ProtoBuf.IExtensible
  {
    public Duplicate_UpdateRsp() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.DuplicateProto> _info = new global::System.Collections.Generic.List<ProtoBuf.DuplicateProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.DuplicateProto> info
    {
      get { return _info; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoBuf.DuplicateGroupProto> _group = new global::System.Collections.Generic.List<ProtoBuf.DuplicateGroupProto>();
    [global::ProtoBuf.ProtoMember(2, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.DuplicateGroupProto> group
    {
      get { return _group; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _open_list = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"open_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> open_list
    {
      get { return _open_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_ReliveReq")]
  public partial class Duplicate_ReliveReq : global::ProtoBuf.IExtensible
  {
    public Duplicate_ReliveReq() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_ReliveRsp")]
  public partial class Duplicate_ReliveRsp : global::ProtoBuf.IExtensible
  {
    public Duplicate_ReliveRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_LeaveReq")]
  public partial class Duplicate_LeaveReq : global::ProtoBuf.IExtensible
  {
    public Duplicate_LeaveReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_LeaveRsp")]
  public partial class Duplicate_LeaveRsp : global::ProtoBuf.IExtensible
  {
    public Duplicate_LeaveRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_EnterAreaReq")]
  public partial class Duplicate_EnterAreaReq : global::ProtoBuf.IExtensible
  {
    public Duplicate_EnterAreaReq() {}
    
    private int _area_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_EnterAreaRsp")]
  public partial class Duplicate_EnterAreaRsp : global::ProtoBuf.IExtensible
  {
    public Duplicate_EnterAreaRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_BuyCountReq")]
  public partial class Duplicate_BuyCountReq : global::ProtoBuf.IExtensible
  {
    public Duplicate_BuyCountReq() {}
    
    private int _group_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"group_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int group_id
    {
      get { return _group_id; }
      set { _group_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_BuyCountRsp")]
  public partial class Duplicate_BuyCountRsp : global::ProtoBuf.IExtensible
  {
    public Duplicate_BuyCountRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private int _buy_num = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"buy_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buy_num
    {
      get { return _buy_num; }
      set { _buy_num = value; }
    }
    private int _group_id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"group_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int group_id
    {
      get { return _group_id; }
      set { _group_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_AutoChallengeReq")]
  public partial class Duplicate_AutoChallengeReq : global::ProtoBuf.IExtensible
  {
    public Duplicate_AutoChallengeReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_AutoChallengeRsp")]
  public partial class Duplicate_AutoChallengeRsp : global::ProtoBuf.IExtensible
  {
    public Duplicate_AutoChallengeRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_FightDataRsp")]
  public partial class Duplicate_FightDataRsp : global::ProtoBuf.IExtensible
  {
    public Duplicate_FightDataRsp() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.DupFightDataProto> _fight_data = new global::System.Collections.Generic.List<ProtoBuf.DupFightDataProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"fight_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.DupFightDataProto> fight_data
    {
      get { return _fight_data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_MonsWaveRsp")]
  public partial class Duplicate_MonsWaveRsp : global::ProtoBuf.IExtensible
  {
    public Duplicate_MonsWaveRsp() {}
    
    private int _wave;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"wave", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wave
    {
      get { return _wave; }
      set { _wave = value; }
    }
    private int _sec;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sec", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sec
    {
      get { return _sec; }
      set { _sec = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_MonsNumRsp")]
  public partial class Duplicate_MonsNumRsp : global::ProtoBuf.IExtensible
  {
    public Duplicate_MonsNumRsp() {}
    
    private int _num;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_MonsStateRsp")]
  public partial class Duplicate_MonsStateRsp : global::ProtoBuf.IExtensible
  {
    public Duplicate_MonsStateRsp() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.DupMonsStateProto> _mon_state = new global::System.Collections.Generic.List<ProtoBuf.DupMonsStateProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mon_state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.DupMonsStateProto> mon_state
    {
      get { return _mon_state; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_ReliveNumRsp")]
  public partial class Duplicate_ReliveNumRsp : global::ProtoBuf.IExtensible
  {
    public Duplicate_ReliveNumRsp() {}
    
    private int _count;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_TowerHpRsp")]
  public partial class Duplicate_TowerHpRsp : global::ProtoBuf.IExtensible
  {
    public Duplicate_TowerHpRsp() {}
    
    private int _hp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Duplicate_TransMonsNumRsp")]
  public partial class Duplicate_TransMonsNumRsp : global::ProtoBuf.IExtensible
  {
    public Duplicate_TransMonsNumRsp() {}
    
    private int _trans_num;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"trans_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int trans_num
    {
      get { return _trans_num; }
      set { _trans_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DupBeforAreaProto")]
  public partial class DupBeforAreaProto : global::ProtoBuf.IExtensible
  {
    public DupBeforAreaProto() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private uint _areaId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"areaId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint areaId
    {
      get { return _areaId; }
      set { _areaId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicToCenter_EnterDupReq")]
  public partial class LogicToCenter_EnterDupReq : global::ProtoBuf.IExtensible
  {
    public LogicToCenter_EnterDupReq() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private uint _duplicate_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"duplicate_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint duplicate_id
    {
      get { return _duplicate_id; }
      set { _duplicate_id = value; }
    }
    private int _key_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"key_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int key_type
    {
      get { return _key_type; }
      set { _key_type = value; }
    }
    private ulong _key_value;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"key_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong key_value
    {
      get { return _key_value; }
      set { _key_value = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.DupBeforAreaProto> _area = new global::System.Collections.Generic.List<ProtoBuf.DupBeforAreaProto>();
    [global::ProtoBuf.ProtoMember(5, Name=@"area", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.DupBeforAreaProto> area
    {
      get { return _area; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CenterToLogic_EnterDupRsp")]
  public partial class CenterToLogic_EnterDupRsp : global::ProtoBuf.IExtensible
  {
    public CenterToLogic_EnterDupRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private uint _charId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private uint _duplicate_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"duplicate_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint duplicate_id
    {
      get { return _duplicate_id; }
      set { _duplicate_id = value; }
    }
    private int _key_type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"key_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int key_type
    {
      get { return _key_type; }
      set { _key_type = value; }
    }
    private ulong _key_value;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"key_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong key_value
    {
      get { return _key_value; }
      set { _key_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicToCenter_CreateSceneReq")]
  public partial class LogicToCenter_CreateSceneReq : global::ProtoBuf.IExtensible
  {
    public LogicToCenter_CreateSceneReq() {}
    
    private uint _char_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"char_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint char_id
    {
      get { return _char_id; }
      set { _char_id = value; }
    }
    private uint _duplicate_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"duplicate_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint duplicate_id
    {
      get { return _duplicate_id; }
      set { _duplicate_id = value; }
    }
    private int _key_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"key_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int key_type
    {
      get { return _key_type; }
      set { _key_type = value; }
    }
    private ulong _key_value;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"key_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong key_value
    {
      get { return _key_value; }
      set { _key_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CenterToLogic_CreateSceneRsp")]
  public partial class CenterToLogic_CreateSceneRsp : global::ProtoBuf.IExtensible
  {
    public CenterToLogic_CreateSceneRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private uint _char_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"char_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint char_id
    {
      get { return _char_id; }
      set { _char_id = value; }
    }
    private uint _duplicate_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"duplicate_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint duplicate_id
    {
      get { return _duplicate_id; }
      set { _duplicate_id = value; }
    }
    private int _key_type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"key_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int key_type
    {
      get { return _key_type; }
      set { _key_type = value; }
    }
    private ulong _key_value;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"key_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong key_value
    {
      get { return _key_value; }
      set { _key_value = value; }
    }
    private uint _scene_id = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"scene_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint scene_id
    {
      get { return _scene_id; }
      set { _scene_id = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.DupBeforAreaProto> _area = new global::System.Collections.Generic.List<ProtoBuf.DupBeforAreaProto>();
    [global::ProtoBuf.ProtoMember(7, Name=@"area", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.DupBeforAreaProto> area
    {
      get { return _area; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicToCenter_CreateDuplicateRsp")]
  public partial class LogicToCenter_CreateDuplicateRsp : global::ProtoBuf.IExtensible
  {
    public LogicToCenter_CreateDuplicateRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private uint _scene_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"scene_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint scene_id
    {
      get { return _scene_id; }
      set { _scene_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CenterToLogic_DuplicateNotifyPrepare")]
  public partial class CenterToLogic_DuplicateNotifyPrepare : global::ProtoBuf.IExtensible
  {
    public CenterToLogic_DuplicateNotifyPrepare() {}
    
    private uint _char_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"char_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint char_id
    {
      get { return _char_id; }
      set { _char_id = value; }
    }
    private uint _duplicate_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"duplicate_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint duplicate_id
    {
      get { return _duplicate_id; }
      set { _duplicate_id = value; }
    }
    private uint _scene_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"scene_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint scene_id
    {
      get { return _scene_id; }
      set { _scene_id = value; }
    }
    private int _key_type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"key_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int key_type
    {
      get { return _key_type; }
      set { _key_type = value; }
    }
    private ulong _key_value;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"key_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong key_value
    {
      get { return _key_value; }
      set { _key_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicToCenter_DuplicatePrepareRsp")]
  public partial class LogicToCenter_DuplicatePrepareRsp : global::ProtoBuf.IExtensible
  {
    public LogicToCenter_DuplicatePrepareRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private uint _char_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"char_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint char_id
    {
      get { return _char_id; }
      set { _char_id = value; }
    }
    private uint _duplicate_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"duplicate_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint duplicate_id
    {
      get { return _duplicate_id; }
      set { _duplicate_id = value; }
    }
    private uint _scene_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"scene_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint scene_id
    {
      get { return _scene_id; }
      set { _scene_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CenterToLogic_DuplicateEnterNotify")]
  public partial class CenterToLogic_DuplicateEnterNotify : global::ProtoBuf.IExtensible
  {
    public CenterToLogic_DuplicateEnterNotify() {}
    
    private uint _char_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"char_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint char_id
    {
      get { return _char_id; }
      set { _char_id = value; }
    }
    private uint _duplicate_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"duplicate_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint duplicate_id
    {
      get { return _duplicate_id; }
      set { _duplicate_id = value; }
    }
    private uint _scene_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"scene_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint scene_id
    {
      get { return _scene_id; }
      set { _scene_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicToCenter_DuplicateEnterRsp")]
  public partial class LogicToCenter_DuplicateEnterRsp : global::ProtoBuf.IExtensible
  {
    public LogicToCenter_DuplicateEnterRsp() {}
    
    private uint _char_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"char_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint char_id
    {
      get { return _char_id; }
      set { _char_id = value; }
    }
    private uint _scene_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"scene_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint scene_id
    {
      get { return _scene_id; }
      set { _scene_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicToCenter_DuplicateLeaveRsp")]
  public partial class LogicToCenter_DuplicateLeaveRsp : global::ProtoBuf.IExtensible
  {
    public LogicToCenter_DuplicateLeaveRsp() {}
    
    private uint _char_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"char_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint char_id
    {
      get { return _char_id; }
      set { _char_id = value; }
    }
    private uint _scene_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"scene_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint scene_id
    {
      get { return _scene_id; }
      set { _scene_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicToCenter_DuplicateBegin")]
  public partial class LogicToCenter_DuplicateBegin : global::ProtoBuf.IExtensible
  {
    public LogicToCenter_DuplicateBegin() {}
    
    private uint _scene_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"scene_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint scene_id
    {
      get { return _scene_id; }
      set { _scene_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicToCenter_DuplicateEnd")]
  public partial class LogicToCenter_DuplicateEnd : global::ProtoBuf.IExtensible
  {
    public LogicToCenter_DuplicateEnd() {}
    
    private uint _scene_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"scene_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint scene_id
    {
      get { return _scene_id; }
      set { _scene_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicToCenter_DuplicateDestory")]
  public partial class LogicToCenter_DuplicateDestory : global::ProtoBuf.IExtensible
  {
    public LogicToCenter_DuplicateDestory() {}
    
    private uint _scene_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"scene_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint scene_id
    {
      get { return _scene_id; }
      set { _scene_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}