//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoBuffer/Package.proto
// Note: requires additional types generated from: ProtoBuffer/ComProtocol.proto
// Note: requires additional types generated from: ProtoBuffer/ClientToServerCmd.proto
// Note: requires additional types generated from: Common/ComDefine.proto
namespace ProtoBuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackageUpdateInfo")]
  public partial class PackageUpdateInfo : global::ProtoBuf.IExtensible
  {
    public PackageUpdateInfo() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo> _item_list = new global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo> item_list
    {
      get { return _item_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackageInfoReq")]
  public partial class PackageInfoReq : global::ProtoBuf.IExtensible
  {
    public PackageInfoReq() {}
    
    private int _package_label;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"package_label", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int package_label
    {
      get { return _package_label; }
      set { _package_label = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackageInfoRet")]
  public partial class PackageInfoRet : global::ProtoBuf.IExtensible
  {
    public PackageInfoRet() {}
    
    private int _package_label;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"package_label", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int package_label
    {
      get { return _package_label; }
      set { _package_label = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo> _item_list = new global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"item_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo> item_list
    {
      get { return _item_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackageLabelInfoRet")]
  public partial class PackageLabelInfoRet : global::ProtoBuf.IExtensible
  {
    public PackageLabelInfoRet() {}
    
    private int _init_equip_grid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"init_equip_grid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int init_equip_grid
    {
      get { return _init_equip_grid; }
      set { _init_equip_grid = value; }
    }
    private int _init_daily_grid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"init_daily_grid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int init_daily_grid
    {
      get { return _init_daily_grid; }
      set { _init_daily_grid = value; }
    }
    private int _init_material_grid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"init_material_grid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int init_material_grid
    {
      get { return _init_material_grid; }
      set { _init_material_grid = value; }
    }
    private int _init_task_grid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"init_task_grid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int init_task_grid
    {
      get { return _init_task_grid; }
      set { _init_task_grid = value; }
    }
    private int _expand_grid;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"expand_grid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int expand_grid
    {
      get { return _expand_grid; }
      set { _expand_grid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackageUpdateExpandRet")]
  public partial class PackageUpdateExpandRet : global::ProtoBuf.IExtensible
  {
    public PackageUpdateExpandRet() {}
    
    private int _expand_grid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"expand_grid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int expand_grid
    {
      get { return _expand_grid; }
      set { _expand_grid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackageSortReq")]
  public partial class PackageSortReq : global::ProtoBuf.IExtensible
  {
    public PackageSortReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackageSortRet")]
  public partial class PackageSortRet : global::ProtoBuf.IExtensible
  {
    public PackageSortRet() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackageSellReq")]
  public partial class PackageSellReq : global::ProtoBuf.IExtensible
  {
    public PackageSellReq() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.ItemSellProto> _sell = new global::System.Collections.Generic.List<ProtoBuf.ItemSellProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"sell", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.ItemSellProto> sell
    {
      get { return _sell; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackageSellRet")]
  public partial class PackageSellRet : global::ProtoBuf.IExtensible
  {
    public PackageSellRet() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackageUseReq")]
  public partial class PackageUseReq : global::ProtoBuf.IExtensible
  {
    public PackageUseReq() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _num = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackageUseRet")]
  public partial class PackageUseRet : global::ProtoBuf.IExtensible
  {
    public PackageUseRet() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackageUpdateRet")]
  public partial class PackageUpdateRet : global::ProtoBuf.IExtensible
  {
    public PackageUpdateRet() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo> _item_list = new global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo> item_list
    {
      get { return _item_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PakcagePickupDropReq")]
  public partial class PakcagePickupDropReq : global::ProtoBuf.IExtensible
  {
    public PakcagePickupDropReq() {}
    
    private readonly global::System.Collections.Generic.List<uint> _dropLst = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"dropLst", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> dropLst
    {
      get { return _dropLst; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PakcagePickupDropRet")]
  public partial class PakcagePickupDropRet : global::ProtoBuf.IExtensible
  {
    public PakcagePickupDropRet() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerEquipInfoReq")]
  public partial class PlayerEquipInfoReq : global::ProtoBuf.IExtensible
  {
    public PlayerEquipInfoReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerEquipInfoRet")]
  public partial class PlayerEquipInfoRet : global::ProtoBuf.IExtensible
  {
    public PlayerEquipInfoRet() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo> _equip_info = new global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"equip_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo> equip_info
    {
      get { return _equip_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerEquipDressReq")]
  public partial class PlayerEquipDressReq : global::ProtoBuf.IExtensible
  {
    public PlayerEquipDressReq() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _pos = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerEquipDressRet")]
  public partial class PlayerEquipDressRet : global::ProtoBuf.IExtensible
  {
    public PlayerEquipDressRet() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerEquipUndressReq")]
  public partial class PlayerEquipUndressReq : global::ProtoBuf.IExtensible
  {
    public PlayerEquipUndressReq() {}
    
    private int _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerEquipUndressRet")]
  public partial class PlayerEquipUndressRet : global::ProtoBuf.IExtensible
  {
    public PlayerEquipUndressRet() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private int _pos = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerEquipUpdateRet")]
  public partial class PlayerEquipUpdateRet : global::ProtoBuf.IExtensible
  {
    public PlayerEquipUpdateRet() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo> _update = new global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"update", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo> update
    {
      get { return _update; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerEquipOneKeyDressReq")]
  public partial class PlayerEquipOneKeyDressReq : global::ProtoBuf.IExtensible
  {
    public PlayerEquipOneKeyDressReq() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.OneKeyDressProto> _dress = new global::System.Collections.Generic.List<ProtoBuf.OneKeyDressProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"dress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.OneKeyDressProto> dress
    {
      get { return _dress; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerEquipOneKeyDressRet")]
  public partial class PlayerEquipOneKeyDressRet : global::ProtoBuf.IExtensible
  {
    public PlayerEquipOneKeyDressRet() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerEquipDelNotify")]
  public partial class PlayerEquipDelNotify : global::ProtoBuf.IExtensible
  {
    public PlayerEquipDelNotify() {}
    
    private readonly global::System.Collections.Generic.List<int> _pos = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> pos
    {
      get { return _pos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_StrenReq")]
  public partial class EquipForge_StrenReq : global::ProtoBuf.IExtensible
  {
    public EquipForge_StrenReq() {}
    
    private int _equip_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"equip_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equip_type
    {
      get { return _equip_type; }
      set { _equip_type = value; }
    }
    private int _stren_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"stren_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stren_type
    {
      get { return _stren_type; }
      set { _stren_type = value; }
    }
    private int _equip_pos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"equip_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equip_pos
    {
      get { return _equip_pos; }
      set { _equip_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_StrenRsp")]
  public partial class EquipForge_StrenRsp : global::ProtoBuf.IExtensible
  {
    public EquipForge_StrenRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_OneKeyStrenReq")]
  public partial class EquipForge_OneKeyStrenReq : global::ProtoBuf.IExtensible
  {
    public EquipForge_OneKeyStrenReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_OneKeyStrenRsp")]
  public partial class EquipForge_OneKeyStrenRsp : global::ProtoBuf.IExtensible
  {
    public EquipForge_OneKeyStrenRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_RefineReq")]
  public partial class EquipForge_RefineReq : global::ProtoBuf.IExtensible
  {
    public EquipForge_RefineReq() {}
    
    private int _equip_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"equip_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equip_type
    {
      get { return _equip_type; }
      set { _equip_type = value; }
    }
    private int _equip_pos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"equip_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equip_pos
    {
      get { return _equip_pos; }
      set { _equip_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_RefineRsp")]
  public partial class EquipForge_RefineRsp : global::ProtoBuf.IExtensible
  {
    public EquipForge_RefineRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_DigHoleReq")]
  public partial class EquipForge_DigHoleReq : global::ProtoBuf.IExtensible
  {
    public EquipForge_DigHoleReq() {}
    
    private int _equip_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"equip_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equip_type
    {
      get { return _equip_type; }
      set { _equip_type = value; }
    }
    private int _equip_pos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"equip_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equip_pos
    {
      get { return _equip_pos; }
      set { _equip_pos = value; }
    }
    private int _hole_idx;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hole_idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hole_idx
    {
      get { return _hole_idx; }
      set { _hole_idx = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_DigHoleRsp")]
  public partial class EquipForge_DigHoleRsp : global::ProtoBuf.IExtensible
  {
    public EquipForge_DigHoleRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_InlayReq")]
  public partial class EquipForge_InlayReq : global::ProtoBuf.IExtensible
  {
    public EquipForge_InlayReq() {}
    
    private int _equip_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"equip_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equip_type
    {
      get { return _equip_type; }
      set { _equip_type = value; }
    }
    private int _equip_pos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"equip_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equip_pos
    {
      get { return _equip_pos; }
      set { _equip_pos = value; }
    }
    private int _stone_idx;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"stone_idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stone_idx
    {
      get { return _stone_idx; }
      set { _stone_idx = value; }
    }
    private int _hole_idx;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hole_idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hole_idx
    {
      get { return _hole_idx; }
      set { _hole_idx = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_InlayRsp")]
  public partial class EquipForge_InlayRsp : global::ProtoBuf.IExtensible
  {
    public EquipForge_InlayRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_TakeOffReq")]
  public partial class EquipForge_TakeOffReq : global::ProtoBuf.IExtensible
  {
    public EquipForge_TakeOffReq() {}
    
    private int _equip_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"equip_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equip_type
    {
      get { return _equip_type; }
      set { _equip_type = value; }
    }
    private int _equip_pos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"equip_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equip_pos
    {
      get { return _equip_pos; }
      set { _equip_pos = value; }
    }
    private int _hole_idx;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hole_idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hole_idx
    {
      get { return _hole_idx; }
      set { _hole_idx = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_TakeOffRsp")]
  public partial class EquipForge_TakeOffRsp : global::ProtoBuf.IExtensible
  {
    public EquipForge_TakeOffRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_InlayHolyReq")]
  public partial class EquipForge_InlayHolyReq : global::ProtoBuf.IExtensible
  {
    public EquipForge_InlayHolyReq() {}
    
    private int _equip_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"equip_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equip_type
    {
      get { return _equip_type; }
      set { _equip_type = value; }
    }
    private int _equip_pos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"equip_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equip_pos
    {
      get { return _equip_pos; }
      set { _equip_pos = value; }
    }
    private int _stone_idx;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"stone_idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stone_idx
    {
      get { return _stone_idx; }
      set { _stone_idx = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_InlayHolyRsp")]
  public partial class EquipForge_InlayHolyRsp : global::ProtoBuf.IExtensible
  {
    public EquipForge_InlayHolyRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_TakeoffHolyReq")]
  public partial class EquipForge_TakeoffHolyReq : global::ProtoBuf.IExtensible
  {
    public EquipForge_TakeoffHolyReq() {}
    
    private int _equip_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"equip_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equip_type
    {
      get { return _equip_type; }
      set { _equip_type = value; }
    }
    private int _equip_pos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"equip_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equip_pos
    {
      get { return _equip_pos; }
      set { _equip_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_TakeoffHolyRsp")]
  public partial class EquipForge_TakeoffHolyRsp : global::ProtoBuf.IExtensible
  {
    public EquipForge_TakeoffHolyRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_ComposeReq")]
  public partial class EquipForge_ComposeReq : global::ProtoBuf.IExtensible
  {
    public EquipForge_ComposeReq() {}
    
    private int _idx;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int idx
    {
      get { return _idx; }
      set { _idx = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _compose_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"compose_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int compose_id
    {
      get { return _compose_id; }
      set { _compose_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_ComposeRsp")]
  public partial class EquipForge_ComposeRsp : global::ProtoBuf.IExtensible
  {
    public EquipForge_ComposeRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_RecastReq")]
  public partial class EquipForge_RecastReq : global::ProtoBuf.IExtensible
  {
    public EquipForge_RecastReq() {}
    
    private int _equip_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"equip_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equip_type
    {
      get { return _equip_type; }
      set { _equip_type = value; }
    }
    private int _equip_pos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"equip_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equip_pos
    {
      get { return _equip_pos; }
      set { _equip_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_RecastRsp")]
  public partial class EquipForge_RecastRsp : global::ProtoBuf.IExtensible
  {
    public EquipForge_RecastRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_ComposeMaterialReq")]
  public partial class EquipForge_ComposeMaterialReq : global::ProtoBuf.IExtensible
  {
    public EquipForge_ComposeMaterialReq() {}
    
    private int _dst_item_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dst_item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dst_item_id
    {
      get { return _dst_item_id; }
      set { _dst_item_id = value; }
    }
    private int _dst_num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"dst_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dst_num
    {
      get { return _dst_num; }
      set { _dst_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForge_ComposeMaterialRsp")]
  public partial class EquipForge_ComposeMaterialRsp : global::ProtoBuf.IExtensible
  {
    public EquipForge_ComposeMaterialRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}