//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoBuffer/ServerInternalProtocol.proto
// Note: requires additional types generated from: ProtoBuffer/ComProtocol.proto
// Note: requires additional types generated from: Common/ComDefine.proto
namespace ProtoBuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginServerRegiste")]
  public partial class LoginServerRegiste : global::ProtoBuf.IExtensible
  {
    public LoginServerRegiste() {}
    
    private uint _groupId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"groupId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint groupId
    {
      get { return _groupId; }
      set { _groupId = value; }
    }
    private uint _serverId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"serverId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint serverId
    {
      get { return _serverId; }
      set { _serverId = value; }
    }
    private uint _outerPort;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"outerPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint outerPort
    {
      get { return _outerPort; }
      set { _outerPort = value; }
    }
    private string _outerIp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"outerIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string outerIp
    {
      get { return _outerIp; }
      set { _outerIp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicServerRegiste")]
  public partial class LogicServerRegiste : global::ProtoBuf.IExtensible
  {
    public LogicServerRegiste() {}
    
    private uint _server_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"server_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint server_id
    {
      get { return _server_id; }
      set { _server_id = value; }
    }
    private uint _outer_port;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"outer_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint outer_port
    {
      get { return _outer_port; }
      set { _outer_port = value; }
    }
    private string _outer_ip;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"outer_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string outer_ip
    {
      get { return _outer_ip; }
      set { _outer_ip = value; }
    }
    private ProtoBuf.LogicServerRegiste.TYPE _type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoBuf.LogicServerRegiste.TYPE type
    {
      get { return _type; }
      set { _type = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"TYPE")]
    public enum TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIRST", Value=1)]
      FIRST = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RECONNECT", Value=2)]
      RECONNECT = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginServerState")]
  public partial class LoginServerState : global::ProtoBuf.IExtensible
  {
    public LoginServerState() {}
    
    private uint _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicServerState")]
  public partial class LogicServerState : global::ProtoBuf.IExtensible
  {
    public LogicServerState() {}
    
    private uint _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private uint _characterCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"characterCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint characterCount
    {
      get { return _characterCount; }
      set { _characterCount = value; }
    }
    private uint _playerCount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playerCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerCount
    {
      get { return _playerCount; }
      set { _playerCount = value; }
    }
    private uint _enterAccountCount;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"enterAccountCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint enterAccountCount
    {
      get { return _enterAccountCount; }
      set { _enterAccountCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AccountLoginCheckReq")]
  public partial class AccountLoginCheckReq : global::ProtoBuf.IExtensible
  {
    public AccountLoginCheckReq() {}
    
    private string _channel_user_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel_user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_user_id
    {
      get { return _channel_user_id; }
      set { _channel_user_id = value; }
    }
    private uint _session_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"session_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint session_id
    {
      get { return _session_id; }
      set { _session_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AccountLoginCheckRsp")]
  public partial class AccountLoginCheckRsp : global::ProtoBuf.IExtensible
  {
    public AccountLoginCheckRsp() {}
    
    private string _channel_user_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel_user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_user_id
    {
      get { return _channel_user_id; }
      set { _channel_user_id = value; }
    }
    private uint _group_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"group_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint group_id
    {
      get { return _group_id; }
      set { _group_id = value; }
    }
    private string _logic_ip;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"logic_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string logic_ip
    {
      get { return _logic_ip; }
      set { _logic_ip = value; }
    }
    private uint _logic_port;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"logic_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint logic_port
    {
      get { return _logic_port; }
      set { _logic_port = value; }
    }
    private ulong _logic_token;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"logic_token", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong logic_token
    {
      get { return _logic_token; }
      set { _logic_token = value; }
    }
    private uint _session_id;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"session_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint session_id
    {
      get { return _session_id; }
      set { _session_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AccountLogoutNotify")]
  public partial class AccountLogoutNotify : global::ProtoBuf.IExtensible
  {
    public AccountLogoutNotify() {}
    
    private string _channel_user_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel_user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_user_id
    {
      get { return _channel_user_id; }
      set { _channel_user_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicCheckTokenReq")]
  public partial class LogicCheckTokenReq : global::ProtoBuf.IExtensible
  {
    public LogicCheckTokenReq() {}
    
    private string _channel_user_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel_user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_user_id
    {
      get { return _channel_user_id; }
      set { _channel_user_id = value; }
    }
    private ulong _logic_token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"logic_token", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong logic_token
    {
      get { return _logic_token; }
      set { _logic_token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicCheckTokenRsp")]
  public partial class LogicCheckTokenRsp : global::ProtoBuf.IExtensible
  {
    public LogicCheckTokenRsp() {}
    
    private int _retcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private string _channel_user_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"channel_user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_user_id
    {
      get { return _channel_user_id; }
      set { _channel_user_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KickChannelUserNotify")]
  public partial class KickChannelUserNotify : global::ProtoBuf.IExtensible
  {
    public KickChannelUserNotify() {}
    
    private string _channel_user_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel_user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_user_id
    {
      get { return _channel_user_id; }
      set { _channel_user_id = value; }
    }
    private uint _charID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CenterAccountLogoutNotify")]
  public partial class CenterAccountLogoutNotify : global::ProtoBuf.IExtensible
  {
    public CenterAccountLogoutNotify() {}
    
    private ProtoBuf.CenterAccountLogoutNotify.TYPE _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoBuf.CenterAccountLogoutNotify.TYPE type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _channel_user_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"channel_user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_user_id
    {
      get { return _channel_user_id; }
      set { _channel_user_id = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"TYPE")]
    public enum TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TOKEN_EXPIRED", Value=1)]
      TOKEN_EXPIRED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHARACTER_LOGOUT", Value=2)]
      CHARACTER_LOGOUT = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReconnectCheckRequest")]
  public partial class ReconnectCheckRequest : global::ProtoBuf.IExtensible
  {
    public ReconnectCheckRequest() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private string _channel_user_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"channel_user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_user_id
    {
      get { return _channel_user_id; }
      set { _channel_user_id = value; }
    }
    private uint _accountIndex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"accountIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint accountIndex
    {
      get { return _accountIndex; }
      set { _accountIndex = value; }
    }
    private ulong _token;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong token
    {
      get { return _token; }
      set { _token = value; }
    }
    private string _channelId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channelId
    {
      get { return _channelId; }
      set { _channelId = value; }
    }
    private string _userId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReconnectCheckResponse")]
  public partial class ReconnectCheckResponse : global::ProtoBuf.IExtensible
  {
    public ReconnectCheckResponse() {}
    
    private uint _retCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint retCode
    {
      get { return _retCode; }
      set { _retCode = value; }
    }
    private uint _charId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private string _channel_user_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"channel_user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_user_id
    {
      get { return _channel_user_id; }
      set { _channel_user_id = value; }
    }
    private uint _accountIndex;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"accountIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint accountIndex
    {
      get { return _accountIndex; }
      set { _accountIndex = value; }
    }
    private ulong _token;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong token
    {
      get { return _token; }
      set { _token = value; }
    }
    private string _channelId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channelId
    {
      get { return _channelId; }
      set { _channelId = value; }
    }
    private string _userId;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicServerAddressReq")]
  public partial class LogicServerAddressReq : global::ProtoBuf.IExtensible
  {
    public LogicServerAddressReq() {}
    
    private string _app_guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"app_guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string app_guid
    {
      get { return _app_guid; }
      set { _app_guid = value; }
    }
    private string _channel_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private string _user_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginLogicRequest")]
  public partial class LoginLogicRequest : global::ProtoBuf.IExtensible
  {
    public LoginLogicRequest() {}
    
    private uint _connect_index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"connect_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint connect_index
    {
      get { return _connect_index; }
      set { _connect_index = value; }
    }
    private string _channel_user_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"channel_user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_user_id
    {
      get { return _channel_user_id; }
      set { _channel_user_id = value; }
    }
    private ulong _token;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong token
    {
      get { return _token; }
      set { _token = value; }
    }
    private uint _group_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"group_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint group_id
    {
      get { return _group_id; }
      set { _group_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginLogicResponse")]
  public partial class LoginLogicResponse : global::ProtoBuf.IExtensible
  {
    public LoginLogicResponse() {}
    
    private uint _connect_index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"connect_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint connect_index
    {
      get { return _connect_index; }
      set { _connect_index = value; }
    }
    private ProtoBuf.LoginLogicResponse.RESULT _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoBuf.LoginLogicResponse.RESULT result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _channel_user_id = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"channel_user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string channel_user_id
    {
      get { return _channel_user_id; }
      set { _channel_user_id = value; }
    }
    private uint _group_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"group_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint group_id
    {
      get { return _group_id; }
      set { _group_id = value; }
    }
    private uint _switch_server_flag = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"switch_server_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint switch_server_flag
    {
      get { return _switch_server_flag; }
      set { _switch_server_flag = value; }
    }
    private ProtoBuf.LoginLogicResponse.SwitchServerParam _switch_server_param = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"switch_server_param", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.LoginLogicResponse.SwitchServerParam switch_server_param
    {
      get { return _switch_server_param; }
      set { _switch_server_param = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SwitchServerParam")]
  public partial class SwitchServerParam : global::ProtoBuf.IExtensible
  {
    public SwitchServerParam() {}
    
    private uint _character_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"character_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint character_id
    {
      get { return _character_id; }
      set { _character_id = value; }
    }
    private uint _source_scene_template_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"source_scene_template_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint source_scene_template_id
    {
      get { return _source_scene_template_id; }
      set { _source_scene_template_id = value; }
    }
    private float _source_pose_x;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"source_pose_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float source_pose_x
    {
      get { return _source_pose_x; }
      set { _source_pose_x = value; }
    }
    private float _source_pose_y;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"source_pose_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float source_pose_y
    {
      get { return _source_pose_y; }
      set { _source_pose_y = value; }
    }
    private uint _dest_scene_template_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"dest_scene_template_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dest_scene_template_id
    {
      get { return _dest_scene_template_id; }
      set { _dest_scene_template_id = value; }
    }
    private uint _dest_scene_instance_id;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"dest_scene_instance_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dest_scene_instance_id
    {
      get { return _dest_scene_instance_id; }
      set { _dest_scene_instance_id = value; }
    }
    private ulong _dest_scene_enter_key;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"dest_scene_enter_key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong dest_scene_enter_key
    {
      get { return _dest_scene_enter_key; }
      set { _dest_scene_enter_key = value; }
    }
    private float _dest_scene_pos_x;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"dest_scene_pos_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float dest_scene_pos_x
    {
      get { return _dest_scene_pos_x; }
      set { _dest_scene_pos_x = value; }
    }
    private float _dest_scene_pos_y;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"dest_scene_pos_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float dest_scene_pos_y
    {
      get { return _dest_scene_pos_y; }
      set { _dest_scene_pos_y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"RESULT")]
    public enum RESULT
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_LOGIC_SUCESS", Value=0)]
      LOGIN_LOGIC_SUCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_LOGIC_FAIL", Value=1)]
      LOGIN_LOGIC_FAIL = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SwitchServerBeginNotify")]
  public partial class SwitchServerBeginNotify : global::ProtoBuf.IExtensible
  {
    public SwitchServerBeginNotify() {}
    
    private string _channel_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private string _user_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private uint _character_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"character_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint character_id
    {
      get { return _character_id; }
      set { _character_id = value; }
    }
    private uint _source_scene_template_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"source_scene_template_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint source_scene_template_id
    {
      get { return _source_scene_template_id; }
      set { _source_scene_template_id = value; }
    }
    private float _source_pose_x;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"source_pose_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float source_pose_x
    {
      get { return _source_pose_x; }
      set { _source_pose_x = value; }
    }
    private float _source_pose_y;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"source_pose_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float source_pose_y
    {
      get { return _source_pose_y; }
      set { _source_pose_y = value; }
    }
    private uint _dest_logic_service_id;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"dest_logic_service_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dest_logic_service_id
    {
      get { return _dest_logic_service_id; }
      set { _dest_logic_service_id = value; }
    }
    private uint _dest_scene_template_id;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"dest_scene_template_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dest_scene_template_id
    {
      get { return _dest_scene_template_id; }
      set { _dest_scene_template_id = value; }
    }
    private uint _dest_scene_instance_id;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"dest_scene_instance_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dest_scene_instance_id
    {
      get { return _dest_scene_instance_id; }
      set { _dest_scene_instance_id = value; }
    }
    private ulong _dest_scene_enter_key;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"dest_scene_enter_key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong dest_scene_enter_key
    {
      get { return _dest_scene_enter_key; }
      set { _dest_scene_enter_key = value; }
    }
    private float _dest_scene_pos_x;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"dest_scene_pos_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float dest_scene_pos_x
    {
      get { return _dest_scene_pos_x; }
      set { _dest_scene_pos_x = value; }
    }
    private float _dest_scene_pos_y;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"dest_scene_pos_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float dest_scene_pos_y
    {
      get { return _dest_scene_pos_y; }
      set { _dest_scene_pos_y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BroadcastToLogicServer")]
  public partial class BroadcastToLogicServer : global::ProtoBuf.IExtensible
  {
    public BroadcastToLogicServer() {}
    
    private uint _groupId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"groupId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint groupId
    {
      get { return _groupId; }
      set { _groupId = value; }
    }
    private byte[] _msg;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicToCenterCreateChar")]
  public partial class LogicToCenterCreateChar : global::ProtoBuf.IExtensible
  {
    public LogicToCenterCreateChar() {}
    
    private uint _charID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    private ProtoBuf.CharacterDBBaseInfo _base;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"base", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoBuf.CharacterDBBaseInfo @base
    {
      get { return _base; }
      set { _base = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicToCenterDelChar")]
  public partial class LogicToCenterDelChar : global::ProtoBuf.IExtensible
  {
    public LogicToCenterDelChar() {}
    
    private uint _charID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    private string _channel_user_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"channel_user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_user_id
    {
      get { return _channel_user_id; }
      set { _channel_user_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogicToCenterCharSync")]
  public partial class LogicToCenterCharSync : global::ProtoBuf.IExtensible
  {
    public LogicToCenterCharSync() {}
    
    private uint _charID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.CharSyncAttr> _attrlist = new global::System.Collections.Generic.List<ProtoBuf.CharSyncAttr>();
    [global::ProtoBuf.ProtoMember(2, Name=@"attrlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.CharSyncAttr> attrlist
    {
      get { return _attrlist; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo> _equip = new global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"equip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo> equip
    {
      get { return _equip; }
    }
  
    private int _all_equip = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"all_equip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int all_equip
    {
      get { return _all_equip; }
      set { _all_equip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterLogicRequest")]
  public partial class EnterLogicRequest : global::ProtoBuf.IExtensible
  {
    public EnterLogicRequest() {}
    
    private uint _character_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"character_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint character_id
    {
      get { return _character_id; }
      set { _character_id = value; }
    }
    private string _channel_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private string _user_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private ulong _token;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong token
    {
      get { return _token; }
      set { _token = value; }
    }
    private string _channel_user_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"channel_user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_user_id
    {
      get { return _channel_user_id; }
      set { _channel_user_id = value; }
    }
    private ProtoBuf.CharacterDBSimpleInfo _charSimpleInfo;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"charSimpleInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoBuf.CharacterDBSimpleInfo charSimpleInfo
    {
      get { return _charSimpleInfo; }
      set { _charSimpleInfo = value; }
    }
    private int _map_id = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"map_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int map_id
    {
      get { return _map_id; }
      set { _map_id = value; }
    }
    private int _scene_id = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"scene_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int scene_id
    {
      get { return _scene_id; }
      set { _scene_id = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo> _equip = new global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo>();
    [global::ProtoBuf.ProtoMember(9, Name=@"equip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo> equip
    {
      get { return _equip; }
    }
  
    private ProtoBuf.CharacterDBAttrDetailInfo _attr = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.CharacterDBAttrDetailInfo attr
    {
      get { return _attr; }
      set { _attr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogoutLogicRequest")]
  public partial class LogoutLogicRequest : global::ProtoBuf.IExtensible
  {
    public LogoutLogicRequest() {}
    
    private ProtoBuf.LogoutLogicRequest.FLAG _flag;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoBuf.LogoutLogicRequest.FLAG flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private uint _character_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"character_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint character_id
    {
      get { return _character_id; }
      set { _character_id = value; }
    }
    private string _channel_user_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"channel_user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_user_id
    {
      get { return _channel_user_id; }
      set { _channel_user_id = value; }
    }
    private ulong _token;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong token
    {
      get { return _token; }
      set { _token = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"FLAG")]
    public enum FLAG
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGOUT_FLAG_GAMING", Value=0)]
      LOGOUT_FLAG_GAMING = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGOUT_FLAG_KICKOUT", Value=1)]
      LOGOUT_FLAG_KICKOUT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGOUT_FLAG_LOGIN_BREAK", Value=2)]
      LOGOUT_FLAG_LOGIN_BREAK = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGOUT_FLAG_SWITCH_SERVER", Value=3)]
      LOGOUT_FLAG_SWITCH_SERVER = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllocLogicNodeRequest")]
  public partial class AllocLogicNodeRequest : global::ProtoBuf.IExtensible
  {
    public AllocLogicNodeRequest() {}
    
    private uint _character_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"character_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint character_id
    {
      get { return _character_id; }
      set { _character_id = value; }
    }
    private string _channel_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private string _user_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _channel_user_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"channel_user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_user_id
    {
      get { return _channel_user_id; }
      set { _channel_user_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllocLogicNodeResponse")]
  public partial class AllocLogicNodeResponse : global::ProtoBuf.IExtensible
  {
    public AllocLogicNodeResponse() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _character_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"character_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint character_id
    {
      get { return _character_id; }
      set { _character_id = value; }
    }
    private string _channel_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private string _user_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _channel_user_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"channel_user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_user_id
    {
      get { return _channel_user_id; }
      set { _channel_user_id = value; }
    }
    private uint _dst_scene_id = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"dst_scene_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dst_scene_id
    {
      get { return _dst_scene_id; }
      set { _dst_scene_id = value; }
    }
    private uint _dst_map_id = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"dst_map_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dst_map_id
    {
      get { return _dst_map_id; }
      set { _dst_map_id = value; }
    }
    private string _logic_ip = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"logic_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string logic_ip
    {
      get { return _logic_ip; }
      set { _logic_ip = value; }
    }
    private uint _logic_port = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"logic_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint logic_port
    {
      get { return _logic_port; }
      set { _logic_port = value; }
    }
    private uint _logic_token = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"logic_token", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint logic_token
    {
      get { return _logic_token; }
      set { _logic_token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientNotifyToClient")]
  public partial class ClientNotifyToClient : global::ProtoBuf.IExtensible
  {
    public ClientNotifyToClient() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private uint _event;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"event", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint @event
    {
      get { return _event; }
      set { _event = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DBProxyAddrInfo")]
  public partial class DBProxyAddrInfo : global::ProtoBuf.IExtensible
  {
    public DBProxyAddrInfo() {}
    
    private uint _groupId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"groupId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint groupId
    {
      get { return _groupId; }
      set { _groupId = value; }
    }
    private uint _serverId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"serverId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint serverId
    {
      get { return _serverId; }
      set { _serverId = value; }
    }
    private uint _Port;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Port
    {
      get { return _Port; }
      set { _Port = value; }
    }
    private string _Ip;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Ip
    {
      get { return _Ip; }
      set { _Ip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CenterRspSceneId")]
  public partial class CenterRspSceneId : global::ProtoBuf.IExtensible
  {
    public CenterRspSceneId() {}
    
    private uint _retCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"retCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint retCode
    {
      get { return _retCode; }
      set { _retCode = value; }
    }
    private uint _dstSceneId = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dstSceneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dstSceneId
    {
      get { return _dstSceneId; }
      set { _dstSceneId = value; }
    }
    private ProtoBuf.Vector3PB _dstPos = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dstPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.Vector3PB dstPos
    {
      get { return _dstPos; }
      set { _dstPos = value; }
    }
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private uint _port = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }
    private string _token = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private uint _dstMapId = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"dstMapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dstMapId
    {
      get { return _dstMapId; }
      set { _dstMapId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CenterDailyUpdateNotify")]
  public partial class CenterDailyUpdateNotify : global::ProtoBuf.IExtensible
  {
    public CenterDailyUpdateNotify() {}
    
    private ulong _updateDailyTime = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"updateDailyTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong updateDailyTime
    {
      get { return _updateDailyTime; }
      set { _updateDailyTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CenterWeekUpdateNotify")]
  public partial class CenterWeekUpdateNotify : global::ProtoBuf.IExtensible
  {
    public CenterWeekUpdateNotify() {}
    
    private ulong _updateDailyTime = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"updateDailyTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong updateDailyTime
    {
      get { return _updateDailyTime; }
      set { _updateDailyTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}